// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace WebApplication1.DBModels.CO;

public partial class COContext : DbContext
{
    public COContext(DbContextOptions<COContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Departments> Departments { get; set; }

    public virtual DbSet<Employees> Employees { get; set; }

    public virtual DbSet<Salaries> Salaries { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Departments>(entity =>
        {
            entity.HasKey(e => e.DepartmentID).HasName("PK__Departme__B2079BCD9D078FCF");

            entity.Property(e => e.DepartmentID).ValueGeneratedNever();
        });

        modelBuilder.Entity<Employees>(entity =>
        {
            entity.HasKey(e => e.EmployeeID).HasName("PK__Employee__7AD04FF1CB2A495C");

            entity.Property(e => e.EmployeeID).ValueGeneratedNever();

            entity.HasOne(d => d.Department).WithMany(p => p.Employees).HasConstraintName("FK__Employees__Depar__534D60F1");
        });

        modelBuilder.Entity<Salaries>(entity =>
        {
            entity.HasKey(e => e.EmployeeID).HasName("PK__Salaries__7AD04FF16CB7EDCD");

            entity.Property(e => e.EmployeeID).ValueGeneratedNever();

            entity.HasOne(d => d.Employee).WithOne(p => p.Salaries)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Salaries__Employ__5629CD9C");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}