// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApplication1.DBModels.CO;

public partial class Departments
{
    [Key]
    public int DepartmentID { get; set; }

    [Required]
    [StringLength(100)]
    public string DepartmentName { get; set; }

    [InverseProperty("Department")]
    public virtual ICollection<Employees> Employees { get; set; } = new List<Employees>();
}