// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApplication1.DBModels.CO;

public partial class Employees
{
    [Key]
    public int EmployeeID { get; set; }

    public int? DepartmentID { get; set; }

    [Required]
    [StringLength(100)]
    public string EmployeeName { get; set; }

    public DateOnly? HireDate { get; set; }

    [ForeignKey("DepartmentID")]
    [InverseProperty("Employees")]
    public virtual Departments Department { get; set; }

    [InverseProperty("Employee")]
    public virtual Salaries Salaries { get; set; }
}